[book]
title = "KSS PC Club - Club Introduction"
author = "KSS-PC-Club"
description = "古河中等教育学校パソコン部の2022年度部活動紹介です"
language = "ja"
multilingual = false
src = "src"

[output.html]
additional-css= ["src/index.css"]
mathjax-support = true
cname = "introduction.kss-pc.club"